language: python
python:
- 3.6
services:
- docker
install:
- docker build -t max-dimsim .
- docker run -it -d -p 5000:5000 max-dimsim
- sleep 30
before_script:
- pip install pytest requests
script:
- pytest tests/test.py